services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: BeakMaruProto
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: moodtrbl
      MYSQL_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
  backend:
    image: moodtrbl/maru:test
    container_name: maru-container
    ports:
      - "80:80"
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/BeakMaruProto?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root