spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:mysql://localhost:3306/BeakMaruProto?serverTimezone=Asia/Seoul
    username: root
    password: root
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/schema/db-init.sql
      platform: mysql
  logging:
    level:
      io.asyncer.r2dbc.mysql: INFO
      io.asyncer.r2dbc.mysql.QUERY: DEBUG

---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:mysql://localhost:3306/BeakMaruProto?serverTimezone=Asia/Seoul
    username: root
    password: root
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/schema/test.sql
      platform: mysql
  logging:
    level:
      io.asyncer.r2dbc.mysql: INFO
      io.asyncer.r2dbc.mysql.QUERY: DEBUG

