spring:
  profiles:
    active: test
---
server:
  port: 80

spring:
  config:
    activate:
      on-profile: deploy
  r2dbc:
    url: r2dbc:mysql://43.201.215.174:3306/BeakMaruProto?serverTimezone=Asia/Seoul
    username: root
    password: root
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath*:db-init.sql
#      platform: mysql
  logging:
    level:
      io.asyncer.r2dbc.mysql: INFO
      io.asyncer.r2dbc.mysql.QUERY: DEBUG
  data:
    redis:
      host: 43.201.215.174
      port: 6379

---
server:
  port: 80

spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:mysql://localhost:3307/BeakMaruProto?serverTimezone=Asia/Seoul
    username: root
    password: root
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath*:db-init.sql
#      platform: mysql
  logging:
    level:
      io.asyncer.r2dbc.mysql: INFO
      io.asyncer.r2dbc.mysql.QUERY: DEBUG
  data:
    redis:
      host: localhost
      port: 6379

---
server:
  servlet:
    session:
      cookie:
        name: JSESSIONID

spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:mysql://localhost:3306/BeakMaruProto?serverTimezone=Asia/Seoul
    username: root
    password: root
  sql:
    init:
      mode: always
      schema-locations: classpath*:schema/db-init.sql
      platform: mysql
  logging:
    level:
      io.asyncer.r2dbc.mysql: INFO
      io.asyncer.r2dbc.mysql.QUERY: DEBUG
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb+srv://root:root@marucluster.8mkhq.mongodb.net/?retryWrites=true&w=majority&appName=MaruCluster
      database: chat
  session:
    store-type: redis
    redis:
      namespace: shboard:session
      flush-mode: immediate

