GRANT ALL PRIVILEGES ON *.* TO '%'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS BeakMaruProto;
USE BeakMaruProto;

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS member;
CREATE TABLE member (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    student_number DECIMAL NOT NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL
);

DROP TABLE IF EXISTS follow;
CREATE TABLE follow (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    from_id BIGINT NOT NULL,
    to_id BIGINT NOT NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    FOREIGN KEY (from_id) REFERENCES member(id),
    FOREIGN KEY (to_id) REFERENCES member(id)
);

SET FOREIGN_KEY_CHECKS=1;